// Mocks generated by Mockito 5.4.4 from annotations
// in fate_app/test/features/file_managment/data/repositories/file_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fate_app/features/file_managment/data/datasources/file_lds_intrerface.dart'
    as _i2;
import 'package:fate_app/features/file_managment/domain/usecases/save_pdf.dart'
    as _i5;
import 'package:file_picker/file_picker.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FileLDS].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileLDS extends _i1.Mock implements _i2.FileLDS {
  @override
  _i3.Future<String?> save(_i4.PlatformFile? file) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [file],
        ),
        returnValue: _i3.Future<String?>.value(),
        returnValueForMissingStub: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> savePdf(_i5.PdfParams? params) => (super.noSuchMethod(
        Invocation.method(
          #savePdf,
          [params],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? path) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
